#[Backend]
backend = "auto"
transition_mode = "static"

#[Smoothing]
smoothing = true
startup_duration = 0.5
shutdown_duration = 0.5
adaptive_interval = 1

#[Static config]
static_temp = 6500
static_gamma = 100

#[Manual transitions]
sunset = "19:00:00"
sunrise = "07:00:00"
transition_duration = 45
